name: build and test feature branch
on:
  pull_request:
    branches: [ develop ]
    types: [ opened, reopened ]
jobs: 
  build-feature:
    runs-on: ubuntu-latest
    steps:
      - name: pull and checkout from git repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: setup java 17 
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: build with maven
        run: |
          mvn clean test package
          echo "build with maven"

